"""empty message

Revision ID: 64df92323f23
Revises: 59fa218f5439
Create Date: 2024-11-28 22:35:17.166119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64df92323f23'
down_revision = '59fa218f5439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
