"""empty message

Revision ID: 59fa218f5439
Revises: 4fe52e94e908
Create Date: 2024-11-28 22:13:39.550952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fa218f5439'
down_revision = '4fe52e94e908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_movies', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
